repos:
    - repo: https://github.com/asottile/reorder_python_imports
      rev: v1.3.4
      hooks:
          - id: reorder-python-imports
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.0.0
      hooks:
          - id: check-ast
          - id: check-docstring-first
          - id: check-executables-have-shebangs
          - id: check-json
          - id: check-merge-conflict
          - id: check-yaml
          - id: debug-statements
          - id: end-of-file-fixer
          - id: trailing-whitespace
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.8.1
      hooks:
          - id: flake8
            additional_dependencies:
            -   flake8-bugbear==18.8.0
            -   flake8-comprehensions==1.4.1
            -   flake8-tidy-imports==1.1.0
    - repo: https://github.com/asottile/pyupgrade
      rev: v1.11.0
      hooks:
        - id: pyupgrade
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.770
      hooks:
        - id: mypy
